JSV.addLang('sys', {
	apStatus : {
		ING : 'In Progress',
		END : 'Complete',
		CANCEL : 'Cancel',
		RETURN : 'Withdraw',
		REJECT : 'Reject',
		TEMP : 'Temporary Save',
		HOLD : 'Hold',
		ARRIVE : 'Arrival',
		LINK_CANCEL : 'Cancel Receving'
	},
	apStep : {
		AP : 'Approval',
		CP : 'Agreement',
		AD : 'Inspection',
		DCP : 'Cooperation',
		RCV : 'Receiving',
		LINK_CANCEL : 'Cancel Receving',
		DC : 'Mandate'
	},
	lineStatus : {
		READY : 'Ready',
		ING : 'In Progress',
		SIGN : 'Approval',
		HOLD : 'Hold',
		REJECT : 'Reject',
		LINK_CANCEL : 'Cancel Receving'
	},
	acctYn : {
		Y : 'Received',
		N : 'Not Received'
	},
	scrtType: {
		ALL : 'Public',
		DEPT : 'Department Disclosure',
		PART : 'Partial Disclosure',
		CLOSED : 'Private'
	},
});
JSV.addLang('nav', {
	undecided : 'Undecided Box',
	decided : 'Decided Box',
	finished : 'Personal Box',
	enterprise : 'Company Box',
	dprtDoc : 'Department Box',
	preview : 'Preview Box',
	shared : 'Share Box',
	referenced : 'Reference Box',
	received : 'Incoming Box',
	sended : 'Outgoing Box',
	adminDoc : 'Approval Doc Mgmt',
	draft : 'Draft Box',
	dprtAdminDoc:'Doc Box Mgmt',
	transfer : '문서함분류 관리',
	exprDoc:'Deleted Doc Box Mgmt',
});
JSV.addLang('btn', {
	'001' : 'Add',
	'002' : 'Del',
	'003' : 'Save',
	'004' : 'Approval',
	'005' : 'All',
	'006' : '1 month',
	'007' : '2 months',
	'008' : '1 year',
	'009' : '2 years',
	'010' : 'Move',
	'011' : 'Cancel',
	'012' : 'Mandate',
	'013' : 'Agreement',
	'014' : 'Receive',
	'015' : 'Reject',
	'016' : 'Edit',
	'017' : 'Appr',
	'018' : 'Agree',
	'019' : 'Receive',
	'020' : 'Add',
	'021' : 'Del',
	'022' : 'Up',
	'023' : 'Down',
	'024' : 'Create a personal Approval Line with the current Approval Line',
	'025' : 'Confirm',
	'026' : 'Approval Information',
	'027' : 'Write',
	'028' : 'Transfer',
	'029' : 'Registration',
	'030' : 'Inspect',
	'031' : 'Cancel Receiving',
	'032' : '가',
	'033' : '나',
	'034' : '다',
	'035' : '라',
	'036' : '마',
	'037' : '바',
	'038' : '사',
	'039' : '아',
	'040' : '자',
	'041' : '카',
	'042' : '타',
	'043' : '파',
	'044' : '하',
	'045' : 'Close'
});
JSV.addLang('doc', {
	'exprMonth' : '6:6 months,12:1 year,24:2 years,60:5 years,120:10 years,240:20 years,-1:Permanent',
	'001' : 'File Name',
	'002' : 'File Size',
	'003' : 'File Count',
	'004' : 'Count',
	'005' : 'Select image',
	'006' : '[Representative]',
	'007' : 'There are no results to display in the list.',
	'008' : 'Receiving History',
	'009' : 'Title',
	'010' : 'Drafter',
	'011' : 'Doc Number',
	'012' : 'Cancel input',
	'013' : 'Search',
	'014' : 'Advanced',
	'015' : 'Expand',
	'016' : 'Fold',
	'017' : 'Initialize search options',
	'018' : 'Select the document in the Draft Box',
	'019' : 'Approval',
	'020' : 'Form Name',
	'021' : 'ALL',
	'022' : 'Req Date',
	'023' : 'Calendar',
	'024' : '1 year',
	'025' : '2 years',
	'026' : 'Approval Status',
	'027' : 'tot ',
	'028' : ' cnt',
	'029' : 'Sort Ascending',
	'030' : 'Sort Descending',
	'031' : 'Representative',
	'032' : 'Modified',
	'033' : 'Approval password',
	'034' : 'Reason for modification',
	'035' : 'Opinion',
	'036' : 'Number of Characters',
	'037' : 'Approval Line Setting',
	'038' : 'Individual Approval Line Setting',
	'039' : 'Specify Destination',
	'040' : 'Specify Reception',
	'041' : 'Add User',
	'042' : 'Organization',
	'043' : 'My Approval',
	'044' : 'User',
	'045' : 'Initialization',
	'046' : 'Name',
	'047' : 'Department',
	'048' : 'Job Title',
	'049' : 'Approva Line',
	'050' : 'Destination',
	'051' : 'Step',
	'052' : 'Information',
	'053' : 'Basic',
	'054' : 'Manager',
	'055' : 'Person',
	'056' : 'Dprt',
	'057' : 'Draft',
	'058' : 'Select related documents',
	'059' : 'persons',
	'060' : 'Comp Date',
	'061' : '※ Check the materials you want and click the Add button.',
	'062' : 'Manager Setting',
	'063' : 'Representative Setting',
	'064' : 'Manage',
	'065' : 'Representative',
	'066' : 'Form Editor',
	'067' : 'Basic Information',
	'068' : 'Document Number Format',
	'069' : 'Document Number Length',
	'070' : 'Multiple Selection',
	'071' : 'Approval Title',
	'072' : 'Approval Cube Number',
	'073' : 'Max Length',
	'074' : 'Height(px)',
	'075' : 'Width(px)',
	'076' : 'Default Value',
	'077' : 'Read only',
	'078' : 'Required check',
	'079' : 'Singular',
	'080' : 'Plural',
	'081' : 'year month day',
	'082' : 'year:month:day',
	'083' : 'year.month.day',
	'084' : 'year/month/day',
	'085' : 'year-month-day',
	'086' : 'All',
	'087' : 'Number',
	'088' : 'Registration',
	'089' : 'SQL Edit Window',
	'090' : 'Public',
	'091' : 'Department Disclosure',
	'092' : 'Partial Disclosure',
	'093' : 'Private',
	'094' : 'Security Settings',
	'095' : 'Component Properties',
	'096' : 'Add/Del',
	'097' : '6 months',
	'098' : '5 years',
	'099' : '10 years',
	'100' : '20 years',
	'101' : 'Permenant',
	'102' : 'Reg Date',
	'103' : 'Writer',
	'104' : 'Use',
	'105' : 'Not Used',
	'106' : 'Approval Form Box',
	'107' : 'Public Form Box',
	'108' : 'It manages the e-approval documents to be modified or rejected.',
	'109' : 'Addiction',
	'110' : 'Selected documents',
	'111' : 'Select the receiving mail organization',
	'112' : 'Organization List',
	'113' : 'Organization name',
	'114' : 'Organization ID',
	'115' : 'Language',
	'116' : 'Joined Date',
	'117' : 'Enter your opinion',
	'118' : 'Edit approval line',
	'119' : 'External Interworking key',
	'120' : 'Cooperation',
	'121' : 'Number',
	'122' : 'Category box to display does not exist.',
	'123' : 'Document Number',	
	'124' : 'Document management',
	'125' : 'Cooperation',
	'126' : 'Not approved',
	'127' : 'Specify Distribution',
	'128' : 'Receiving Number',
	'129' : 'Originating agency',
	'130' : 'Shipping number',
	'131' : 'Whole documents',
	'132' : 'Basic Category Box',
	'133' : 'Please select.',
	'134' : 'Email',
	'135' : 'IP',
	'136' : 'Attached file',
	'137' : '사번'
});
JSV.addLang('msg', {
	'001' : 'Please check the date range again.',
	'002' : 'The page number that can not be moved.\nPlease re-enter.',
	'003' : 'It is not a permitted data type.',
	'004' : 'It is not a valid data type.',
	'005' : 'Please enter the document number length.',
	'006' : 'Please enter document number format.',
	'007' : 'Please enter.',
	'008' : 'Please enter only numbers.',
	'009' : 'Saved.',
	'010' : ' only numbers can be entered in the item.',
	'011' : 'Please specify the format.',
	'012' : '[Date] Mandatory input value. Please enter.',
	'013' : '[Document Title] Required input value. Please enter',
	'014' : 'Please enter the approval password.',
	'015' : 'Please re-enter the approval password.',
	'016' : 'Please register your opinion.',
	'017' : 'Please enter your username.',
	'018' : 'Please select approver.',
	'019' : 'Please select agreement.',
	'020' : 'Please select mandator.',
	'021' : 'Please select receiver.',
	'022' : 'Has already been added.',
	'023' : 'Only one acceptor is allowed.',
	'024' : 'Please select the individual approval line.',
	'025' : 'The approval line is initialized and set.\nDo you want to proceed?',
	'026' : 'If a receiver is specified, the personal approval line can not be saved.',
	'027' : 'Please select an approval line.',
	'028' : 'Please select approver to move.',
	'029' : 'Please set the approval line..',
	'030' : 'The last approval line should be set to [receiver].',
	'031' : 'The last approval line should be set in the order of [approver], [receiver].',
	'032' : 'Please set [approver].',
	'033' : 'The approval line before [receiver] should be set to [approver].',
	'034' : 'The last approval line should be set to [approver].',
	'035' : 'Please enter your search term.',
	'036' : 'The same document is added to the document.',
	'037' : 'Please select a related document to add.',
	'038' : 'Please select a related document to delete.',
	'039' : 'Please add related documents.',
	'040' : 'Please set the user or department.',
	'041' : 'Please select the user or department.',
	'042' : ' has been added.',
//	'043' : '담당자를 설정해주세요.',
//	'044' : '대결자를 설정해주세요.',
	'045' : 'You exceeded the limit number of characters.',
	'046' : 'Please select which department or user you want to set security on.',
	'047' : 'This is a required input value.',
	'048' : 'This is not a valid email format.',
	'049' : 'This is not a valid URL format.',
	'050' : 'Please enter your Google mail.',
	'051' : 'Please add an organization to send mail to.',
	'052' : 'Permitted attachment size exceeded.',
	'053' : 'This is an invalid file type.',
	'054' : 'This is not a valid number format.',
	'055' : 'Are you sure you want to delete?',
	'056' : 'The total file size allowed has been exceeded.',
	'057' : 'The number of allowed files has been exceeded.',
	'058' : 'The previous approval line of the acceptor should be set to [approver].',
	//'059' : '접수자는 한명만 가능 합니다.',
	'060' : 'Your answer has been entered. Do you want to save it?',
	'061' : 'Your comment has been edited. Do you want to save it?',
	'062' : 'Changed component values saved.',
	'063' : 'Please select an organization to delete.',
	'064' : 'Already added cooperation.',
	'065' : 'Approver is ',
	'066' : 'Agreement is ',
	'067' : 'Receiver is ',
	'068' : ' is possible.',
	'069' : 'Only the remaining approval lines except for cooperation or receiver are saved.',
	'070' : 'Duplicate name.',
	'071' : 'The name can not contain a comma.',
	'072' : 'Please enter a mandatory name.',
	'073' : 'Only the approval line except the agreement and cooperation is set,\n',
	'074' : 'The Approver can only be designated as an individual.',
	'075' : 'The Receiver can only be assigned as an individual.',
	'076' : 'Please select Inspector.',
	'077' : 'Inspection must be entered before the last approver.',
	'078' : 'Inspector is ',
	'079' : 'Cooperation is ',
	'080' : 'Only the approval line is set except Inspector,\n',
//	'081' : '협조처를 제외한 결재선만 셋팅되고,\n',
	'082' : 'Please upload an image file.',
	'083' : 'If you have multiple Inspectors, you must have a sequential order.',
	'084' : '[Category box] Please select a category.',
	'085' : 'Please select..',
	'086' : 'The current approver does not exist.\nPlease try again.',
	'087' : 'If there are multiple receivers, they must have consecutive sequences.',
	'088' : '[Category Code] Required input value.',
	'089' : '[Company Logo] Does not exist.',
	'090' : '[Company seal] Does not exist.',
	'091' : 'This is a required input value. Please enter.',
	'092' : 'This is not a valid IP format.',
	'093' : 'Please set the default Category Box Management.',
	'094' : 'Please add a user.',
	'095' : 'Do you want to download the online editing module?\nYou may see this message even if the application of the file you are trying to edit is loading later. If you have already installed it, please click Cancel and then click the edit link again.',
	'096' : ' are signed in.',
	'097' : ' are signed out.',
});
JSV.addLang('linkmsg', {
	'001' : 'Please add a debit item.',
	'002' : 'Please add credit item.',
	'003' : 'The debit and credit values do not match. \nPlease check.',
});